default:
    py_version: "python3/bin/python"
    E4_db_loc: '/Users/mrosen44/OneDrive - Johns Hopkins University/Data_Analysis/PICU_CAL/E4_Data/'
    E4_db_name: 'PICU_E4_data.db'
    RLTLS_db_loc: '/Users/mrosen44/OneDrive - Johns Hopkins University/RTLS_Data/'
    RTLS_db_name: 'RTLS_030819.db'
    E4_download_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Project_CollectiveAllostaticLoad/PICU Data Collection/'
    tracking_file_loc: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Project_CollectiveAllostaticLoad/PICU Data Collection/'
    tracking_file: 'PICU_Device_Assignment.xlsx'
