default:
    py_version: "python3/bin/python"
    tracking_file: 'PICU_Device_Assignment.xlsx'
    # Currently these are only accessible to Mike
    E4_db_loc: "/Users/mrosen44/Documents/Data_Analysis_Local/PICU_CAL/data/" #'/Users/mrosen44/OneDrive - Johns Hopkins University/Data_Analysis/PICU_CAL/E4_Data/'
    E4_db_name: 'PICU_E4_data.db'
    RTLS_db_loc: '/Users/mrosen44/OneDrive - Johns Hopkins University/RTLS_Data/'
    RTLS_db_name: 'RTLS_030819.db'

custom_process:
    tracking_file: 'Custom_Process_PICU_Device_Assignment.xlsx'

mike:
    inherits: custom_process
    E4_download_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Project_CollectiveAllostaticLoad/PICU Data Collection/'
    tracking_file_loc: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Project_CollectiveAllostaticLoad/PICU Data Collection/'

salar:
    inherits: custom_process
    E4_download_path: # Add path for you
    tracking_file_loc: # Add path for you
