default:
    py_version: "python3/bin/python"
    tracking_file: 'PICU_Device_Assignment.xlsx'
    # Currently these are only accessible to Mike
    E4_db_loc: "/Users/mrosen44/Documents/Data_Analysis_Local/PICU_CAL/data/" #'/Users/mrosen44/OneDrive - Johns Hopkins University/Data_Analysis/PICU_CAL/E4_Data/'
    E4_db_name: 'PICU_E4_data.db'
    RTLS_db_u: 'script_monkey'
    RTLS_db_pw: 'cocobolo32'
    RTLS_db_loc: '/Users/mrosen44/OneDrive - Johns Hopkins University/RTLS_Data/'
    RTLS_db_name: 'RTLS_030819.db'
    Survey_f_name: "PICU_RawSurveyData_update_061821.csv"
    analysis_file: 'Custom_Process_PICU_Device_Assignment.xlsx'
    sync_sampling_freq: 'S'
    sync_corr_method: 'pearson'
    sync_use_residuals: FALSE
    sync_measures: !expr c('EDA','HR')
    sync_metrics: !expr c('AR','Driver','Empath')
    sync_offset: 50 # Seconds to lag synchrony

mike:
    inherits: default
    E4_download_path: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Project_CollectiveAllostaticLoad/PICU Data Collection/'
    tracking_file_loc: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Project_CollectiveAllostaticLoad/PICU Data Collection/'
    survey_f_loc: '/Users/mrosen44/Johns Hopkins/Salar Khaleghzadegan - Project_CollectiveAllostaticLoad/Data_Analysis/'

salar:
    inherits: default
    E4_download_path: '/Users/skhaleg1/OneDrive - Johns Hopkins/Project_CollectiveAllostaticLoad/PICU Data Collection/'
    tracking_file_loc: '/Users/skhaleg1/OneDrive - Johns Hopkins/Project_CollectiveAllostaticLoad/PICU Data Collection/'
    survey_f_loc: '/Users/skhaleg1/OneDrive - Johns Hopkins/Project_CollectiveAllostaticLoad/Data_Analysis/'
